# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kataki\OneDrive\Masaüstü\python 1 deneme\hesapmakinası.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(199, 255, 201);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toplama_btn = QtWidgets.QPushButton(self.centralwidget)
        self.toplama_btn.setGeometry(QtCore.QRect(130, 250, 161, 61))
        self.toplama_btn.setObjectName("toplama_btn")
        self.cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.cikarma.setGeometry(QtCore.QRect(330, 250, 161, 61))
        self.cikarma.setObjectName("cikarma")
        self.sayi_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.sayi_1.setGeometry(QtCore.QRect(130, 150, 191, 31))
        self.sayi_1.setText("")
        self.sayi_1.setObjectName("sayi_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 150, 51, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(26, 200, 51, 41))
        self.label_2.setObjectName("label_2")
        self.sayi_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.sayi_2.setGeometry(QtCore.QRect(130, 210, 191, 31))
        self.sayi_2.setText("")
        self.sayi_2.setObjectName("sayi_2")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(130, 340, 161, 61))
        self.sonuc.setObjectName("sonuc")
        self.sifirla = QtWidgets.QPushButton(self.centralwidget)
        self.sifirla.setGeometry(QtCore.QRect(540, 250, 161, 61))
        self.sifirla.setObjectName("sifirla")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toplama_btn.setText(_translate("MainWindow", "toplama"))
        self.cikarma.setText(_translate("MainWindow", "çıkarma"))
        self.label.setText(_translate("MainWindow", "sayı 1 "))
        self.label_2.setText(_translate("MainWindow", "sayı 2 "))
        self.sonuc.setText(_translate("MainWindow", "sonuç"))
        self.sifirla.setText(_translate("MainWindow", "sıfırla"))
